# Generated by Django 5.1 on 2024-09-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='time_slots',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='book',
            name='phone_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='book',
            name='symptoms',
            field=models.TextField(),
        ),
    ]
