# Generated by Django 5.1 on 2024-08-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=250)),
                ('phone_no', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, choices=[('querry', 'Query'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=50, null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
