# Generated by Django 5.1 on 2024-08-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='type',
            field=models.CharField(blank=True, choices=[('query', 'Query'), ('feedback', 'Feedback'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
